import React from 'react';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    boxTransaction:{
        width:'100%',
        height:'35%',
        backgroundColor:'#FF5400',
        alignItems:'center',
        justifyContent:'center',
    },
    keyboard:{
        width:'100%',
        height:'65%',
        backgroundColor:'#FF5400'
    },
    keyboardBox:{
        width:'100%',
        height:'100%',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#FFF',
        paddingTop:8,
        borderTopRightRadius:30,
        borderTopLeftRadius:30,
    },


    BoxTransactionDate:{
        width:'100%',
        height:20,
        marginTop:10,
    },
    nextButtomText:{
        fontWeight:'bold',
        fontSize:15,
        color:'#FFF'
    },
    nextButton:{
        width:'70%',
        height:50,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:50,
        backgroundColor:'#FF5400'
    },
    categoriesValues:{
        width:'90%',
        height:'80%',
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
    },
    keyText:{
        fontSize:30,
        color:'#FF5400',
        fontWeight:'bold'
    },
    BackspaceIcon:{
        width:30,
        height:30
    },
    KeyboardKey:{
        width:'33%',
        height:'24%',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#FFF'
    },
    headerBoxContainer:{
        width:'90%',
        height:'80%',
    },
    boxHeaderTop:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    TextAddTransaction:{
        fontSize:20,
        fontWeight:'bold',
        color:'#FFF'
    },
    TextAddDespense:{
        fontSize:14,
        color:'#fffcf2'
    },
    textCancel:{
        color:'#e6e8e6',
        fontSize:18,
        fontWeight:'bold'
    },
    headerBoxCancelButtom:{
        alignItems:'center',
        justifyContent:'center',
    },
    boxValueKey:{
        alignItems:'center',
        flexDirection:'row',
        height:140,
        paddingLeft:20,
    },
    ValueTextAmmount:{
        fontWeight:'bold',
        fontSize:60,
        color:'#FFF'
    },
});